package PDFModule;


/**
* PDFModule/_PDFServiceStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Wednesday, April 29, 2026 12:12:31 PM CEST
*/

public class _PDFServiceStub extends org.omg.CORBA.portable.ObjectImpl implements PDFModule.PDFService
{

  public byte[] fusionner (byte[] pdf1, byte[] pdf2)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("fusionner", true);
                PDFModule.PDFDataHelper.write ($out, pdf1);
                PDFModule.PDFDataHelper.write ($out, pdf2);
                $in = _invoke ($out);
                byte $result[] = PDFModule.PDFDataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return fusionner (pdf1, pdf2        );
            } finally {
                _releaseReply ($in);
            }
  } // fusionner

  public byte[] decouper (byte[] pdf, int pageDebut, int pageFin)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("decouper", true);
                PDFModule.PDFDataHelper.write ($out, pdf);
                $out.write_long (pageDebut);
                $out.write_long (pageFin);
                $in = _invoke ($out);
                byte $result[] = PDFModule.PDFDataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return decouper (pdf, pageDebut, pageFin        );
            } finally {
                _releaseReply ($in);
            }
  } // decouper

  public byte[] supprimerPage (byte[] pdf, int numeroPage)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("supprimerPage", true);
                PDFModule.PDFDataHelper.write ($out, pdf);
                $out.write_long (numeroPage);
                $in = _invoke ($out);
                byte $result[] = PDFModule.PDFDataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return supprimerPage (pdf, numeroPage        );
            } finally {
                _releaseReply ($in);
            }
  } // supprimerPage

  public byte[] ajouterMotDePasse (byte[] pdf, String password)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("ajouterMotDePasse", true);
                PDFModule.PDFDataHelper.write ($out, pdf);
                $out.write_string (password);
                $in = _invoke ($out);
                byte $result[] = PDFModule.PDFDataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return ajouterMotDePasse (pdf, password        );
            } finally {
                _releaseReply ($in);
            }
  } // ajouterMotDePasse

  public byte[] convertirEnImage (byte[] pdf, int numeroPage)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("convertirEnImage", true);
                PDFModule.PDFDataHelper.write ($out, pdf);
                $out.write_long (numeroPage);
                $in = _invoke ($out);
                byte $result[] = PDFModule.PDFDataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return convertirEnImage (pdf, numeroPage        );
            } finally {
                _releaseReply ($in);
            }
  } // convertirEnImage

  public String extraireTexte (byte[] pdf)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("extraireTexte", true);
                PDFModule.PDFDataHelper.write ($out, pdf);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return extraireTexte (pdf        );
            } finally {
                _releaseReply ($in);
            }
  } // extraireTexte

  public byte[] creerPDF (String contenu)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("creerPDF", true);
                $out.write_string (contenu);
                $in = _invoke ($out);
                byte $result[] = PDFModule.PDFDataHelper.read ($in);
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return creerPDF (contenu        );
            } finally {
                _releaseReply ($in);
            }
  } // creerPDF

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PDFModule/PDFService:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     com.sun.corba.se.impl.orbutil.IORCheckImpl.check(str, "PDFModule._PDFServiceStub");
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _PDFServiceStub
