package PDFModule;


/**
* PDFModule/PDFServiceOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Wednesday, April 29, 2026 12:12:31 PM CEST
*/

public interface PDFServiceOperations 
{
  byte[] fusionner (byte[] pdf1, byte[] pdf2);
  byte[] decouper (byte[] pdf, int pageDebut, int pageFin);
  byte[] supprimerPage (byte[] pdf, int numeroPage);
  byte[] ajouterMotDePasse (byte[] pdf, String password);
  byte[] convertirEnImage (byte[] pdf, int numeroPage);
  String extraireTexte (byte[] pdf);
  byte[] creerPDF (String contenu);
} // interface PDFServiceOperations
