package PDFModule;

/**
* PDFModule/PDFServiceHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Wednesday, April 29, 2026 12:12:31 PM CEST
*/

public final class PDFServiceHolder implements org.omg.CORBA.portable.Streamable
{
  public PDFModule.PDFService value = null;

  public PDFServiceHolder ()
  {
  }

  public PDFServiceHolder (PDFModule.PDFService initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = PDFModule.PDFServiceHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    PDFModule.PDFServiceHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return PDFModule.PDFServiceHelper.type ();
  }

}
