package PDFModule;


/**
* PDFModule/PDFService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Wednesday, April 29, 2026 12:12:31 PM CEST
*/

public interface PDFService extends PDFServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface PDFService
