package PDFModule;


/**
* PDFModule/PDFServicePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from PDFService.idl
* Wednesday, April 29, 2026 12:12:31 PM CEST
*/

public abstract class PDFServicePOA extends org.omg.PortableServer.Servant
 implements PDFModule.PDFServiceOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("fusionner", new java.lang.Integer (0));
    _methods.put ("decouper", new java.lang.Integer (1));
    _methods.put ("supprimerPage", new java.lang.Integer (2));
    _methods.put ("ajouterMotDePasse", new java.lang.Integer (3));
    _methods.put ("convertirEnImage", new java.lang.Integer (4));
    _methods.put ("extraireTexte", new java.lang.Integer (5));
    _methods.put ("creerPDF", new java.lang.Integer (6));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // PDFModule/PDFService/fusionner
       {
         byte pdf1[] = PDFModule.PDFDataHelper.read (in);
         byte pdf2[] = PDFModule.PDFDataHelper.read (in);
         byte $result[] = null;
         $result = this.fusionner (pdf1, pdf2);
         out = $rh.createReply();
         PDFModule.PDFDataHelper.write (out, $result);
         break;
       }

       case 1:  // PDFModule/PDFService/decouper
       {
         byte pdf[] = PDFModule.PDFDataHelper.read (in);
         int pageDebut = in.read_long ();
         int pageFin = in.read_long ();
         byte $result[] = null;
         $result = this.decouper (pdf, pageDebut, pageFin);
         out = $rh.createReply();
         PDFModule.PDFDataHelper.write (out, $result);
         break;
       }

       case 2:  // PDFModule/PDFService/supprimerPage
       {
         byte pdf[] = PDFModule.PDFDataHelper.read (in);
         int numeroPage = in.read_long ();
         byte $result[] = null;
         $result = this.supprimerPage (pdf, numeroPage);
         out = $rh.createReply();
         PDFModule.PDFDataHelper.write (out, $result);
         break;
       }

       case 3:  // PDFModule/PDFService/ajouterMotDePasse
       {
         byte pdf[] = PDFModule.PDFDataHelper.read (in);
         String password = in.read_string ();
         byte $result[] = null;
         $result = this.ajouterMotDePasse (pdf, password);
         out = $rh.createReply();
         PDFModule.PDFDataHelper.write (out, $result);
         break;
       }

       case 4:  // PDFModule/PDFService/convertirEnImage
       {
         byte pdf[] = PDFModule.PDFDataHelper.read (in);
         int numeroPage = in.read_long ();
         byte $result[] = null;
         $result = this.convertirEnImage (pdf, numeroPage);
         out = $rh.createReply();
         PDFModule.PDFDataHelper.write (out, $result);
         break;
       }

       case 5:  // PDFModule/PDFService/extraireTexte
       {
         byte pdf[] = PDFModule.PDFDataHelper.read (in);
         String $result = null;
         $result = this.extraireTexte (pdf);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // PDFModule/PDFService/creerPDF
       {
         String contenu = in.read_string ();
         byte $result[] = null;
         $result = this.creerPDF (contenu);
         out = $rh.createReply();
         PDFModule.PDFDataHelper.write (out, $result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:PDFModule/PDFService:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public PDFService _this() 
  {
    return PDFServiceHelper.narrow(
    super._this_object());
  }

  public PDFService _this(org.omg.CORBA.ORB orb) 
  {
    return PDFServiceHelper.narrow(
    super._this_object(orb));
  }


} // class PDFServicePOA
