FROM eclipse-temurin:8-jdk
WORKDIR /app
COPY pdfbox-2.0.30.jar .
COPY fontbox-2.0.30.jar .
COPY commons-logging-1.2.jar .
COPY PDFModule/ ./PDFModule/
COPY *.class .
COPY index.html .
EXPOSE 8080
CMD ["/opt/java/openjdk/bin/java", "-cp", ".:pdfbox-2.0.30.jar:fontbox-2.0.30.jar:commons-logging-1.2.jar", "ServeurHTTP", "-ORBInitialPort", "1050", "-ORBInitialHost", "nameserver"]
